<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="IBM-PF3PELFE" failures="1" tests="4" name="nandeeshFrameWork.SeleniumFrameWorkDesign.Tests.loginErrorValidationsTest" time="24.346" errors="0" timestamp="2024-06-02T22:22:18 IST" skipped="2">
  <testcase classname="nandeeshFrameWork.SeleniumFrameWorkDesign.Tests.loginErrorValidationsTest" name="submitOrder" time="5.593">
    <skipped/>
  </testcase> <!-- submitOrder -->
  <testcase classname="nandeeshFrameWork.SeleniumFrameWorkDesign.Tests.loginErrorValidationsTest" name="submitOrder" time="7.383">
    <skipped/>
  </testcase> <!-- submitOrder -->
  <testcase classname="nandeeshFrameWork.SeleniumFrameWorkDesign.Tests.loginErrorValidationsTest" name="productErrorValidation" time="5.153"/>
  <testcase classname="nandeeshFrameWork.SeleniumFrameWorkDesign.Tests.loginErrorValidationsTest" name="submitOrder" time="6.217">
    <failure message="expected [Incorrect email or password.] but found [Incorrect email password]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email password]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at nandeeshFrameWork.SeleniumFrameWorkDesign.Tests.loginErrorValidationsTest.submitOrder(loginErrorValidationsTest.java:86)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
    </failure>
  </testcase> <!-- submitOrder -->
</testsuite> <!-- nandeeshFrameWork.SeleniumFrameWorkDesign.Tests.loginErrorValidationsTest -->
